//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCA.Common.Resource.AlertResource", typeof(AlertResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem sırasında bir hata meydana geldi.
        /// </summary>
        public static string AnErrorOccurredWhenProcess {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhenProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt İşlemi Başarılı.
        /// </summary>
        public static string CreateIsOk {
            get {
                return ResourceManager.GetString("CreateIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi zaten kayıtlı.
        /// </summary>
        public static string EmailAlreadyExsist {
            get {
                return ResourceManager.GetString("EmailAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email başarıyla gönderilmiştir..
        /// </summary>
        public static string EmailSendAsSuccessfuly {
            get {
                return ResourceManager.GetString("EmailSendAsSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj başarıyla göndrilmiştir..
        /// </summary>
        public static string MessageSendAsSuccessfuly {
            get {
                return ResourceManager.GetString("MessageSendAsSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklik yok.
        /// </summary>
        public static string NoChanges {
            get {
                return ResourceManager.GetString("NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon başarısız.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operasyon başarılı.
        /// </summary>
        public static string SuccessfulOperation {
            get {
                return ResourceManager.GetString("SuccessfulOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Güncelleme İşleme Başarılı.
        /// </summary>
        public static string UpdateIsOk {
            get {
                return ResourceManager.GetString("UpdateIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı veya şifre hatalı.
        /// </summary>
        public static string UserNameOrPasswordIsInCorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIsInCorrect", resourceCulture);
            }
        }
    }
}
